# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Evald < Formula
  desc "Embedded OTel-native trace + eval store for LLM apps (single binary)"
  homepage "https://github.com/lucheeseng827/evald"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-aarch64-apple-darwin.tar.gz"
      sha256 "1a08b4a51bed77e269051b6fa4a4a1d2ca4b61b32bc0995c05dad6b38f778210"
    end
    on_intel do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-x86_64-apple-darwin.tar.gz"
      sha256 "371ee5979ce4df7b008f15dff3c185a6a213f116c88a0446e2b175e2cdaeaca4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-aarch64-unknown-linux-musl.tar.gz"
      sha256 "9929a704d71c3fa67cba50ae40b4c46b90196102358efdf19847ec6b8e758e20"
    end
    on_intel do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-x86_64-unknown-linux-musl.tar.gz"
      sha256 "edf149d53a14289097390e286d580a8b36e475c25cd72a1e58388760b98eb38c"
    end
  end

  def install
    bin.install "evald"
  end

  test do
    assert_match "evald", shell_output("#{bin}/evald version")
  end
end
