# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Evald < Formula
  desc "Embedded OTel-native trace + eval store for LLM apps (single binary)"
  homepage "https://github.com/lucheeseng827/evald"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-aarch64-apple-darwin.tar.gz"
      sha256 "59e3ca72ba5e02d5dbd8d669e6c2dd4ecaf9803b4fddd4def3290fddbac7b2b4"
    end
    on_intel do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-x86_64-apple-darwin.tar.gz"
      sha256 "c07a4a4aa09b317d26919fd3d18904622649529d3b10f11f576ef72e385d1c02"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-aarch64-unknown-linux-musl.tar.gz"
      sha256 "e47993f630e5a3dd9096d2fb0e7ec82b9be7fb88f7b938fdfad6f82263fdb761"
    end
    on_intel do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-x86_64-unknown-linux-musl.tar.gz"
      sha256 "bfcd845e8db5f1b2e1dc40ffd4f73cb0906898a5fab1291975177163b89c6f5e"
    end
  end

  def install
    bin.install "evald"
  end

  test do
    assert_match "evald", shell_output("#{bin}/evald version")
  end
end
