# Generated by .github/workflows/release.yml on each v* tag — do not hand-edit.
class Evald < Formula
  desc "Embedded OTel-native trace + eval store for LLM apps (single binary)"
  homepage "https://github.com/lucheeseng827/evald"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-aarch64-apple-darwin.tar.gz"
      sha256 "40ce43479f3a2e68686ee28f4827228dc44d23ba03655ba1d0253640b8899152"
    end
    on_intel do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-x86_64-apple-darwin.tar.gz"
      sha256 "6a535b7228fbf77bea2970979ca8b2a1f5d1d6c6d6614fd7b535e05c99209285"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-aarch64-unknown-linux-musl.tar.gz"
      sha256 "323e4670d0c13bff3460018780d3125eabed13357bc83d2acc9ad71b8062627f"
    end
    on_intel do
      url "https://github.com/lucheeseng827/evald/releases/download/v#{version}/evald-x86_64-unknown-linux-musl.tar.gz"
      sha256 "de8196e87c1d85b014c71d7d9bc6f0dbc5c73e0e22f030b3e51ee9b7fc12194a"
    end
  end

  def install
    bin.install "evald"
  end

  test do
    assert_match "evald", shell_output("#{bin}/evald version")
  end
end
