//! OTLP/gRPC receiver on :4317 — the gRPC sibling of the :4318 HTTP receiver. gRPC is a
//! standard OTel collector transport, so this covers exporters that only emit OTLP/gRPC.
//!
//! Hosts the OTLP `TraceService` generated by `opentelemetry-proto` (`gen-tonic`). The
//! `export` RPC decodes into the SAME `ExportTraceServiceRequest` the HTTP path uses, so it
//! reuses the one [`crate::normalize`] pass, the blob offload, and the durable
//! [`Store::append`] — a single ingest core behind both listeners. Plaintext h2c (like the
//! :4318 HTTP receiver), for a local endpoint; front it with a TLS-terminating proxy to
//! expose it.

use std::net::SocketAddr;

use opentelemetry_proto::tonic::collector::trace::v1::{
    trace_service_server::{TraceService, TraceServiceServer},
    ExportTraceServiceRequest, ExportTraceServiceResponse,
};
use tonic::{Request, Response, Status};

use crate::{normalize, Store, StoreError};

/// The gRPC receiver: a thin adapter from the OTLP `TraceService` onto the shared store.
#[derive(Clone)]
pub struct TraceReceiver {
    store: Store,
}

impl TraceReceiver {
    pub fn new(store: Store) -> Self {
        Self { store }
    }

    /// Normalize → offload oversized payloads → durably append. Shared by the `export` RPC and
    /// unit-testable without binding a socket. Returns the span count on success.
    async fn ingest(&self, request: ExportTraceServiceRequest) -> Result<usize, StoreError> {
        let mut spans = normalize::normalize_request(&request);
        let count = spans.len();
        self.store.offload_payloads(&mut spans);
        self.store.append(spans).await.map(|()| count)
    }
}

#[tonic::async_trait]
impl TraceService for TraceReceiver {
    async fn export(
        &self,
        request: Request<ExportTraceServiceRequest>,
    ) -> Result<Response<ExportTraceServiceResponse>, Status> {
        match self.ingest(request.into_inner()).await {
            // Full success — an empty `partial_success` means every span was accepted.
            Ok(_) => Ok(Response::new(ExportTraceServiceResponse::default())),
            // Backpressure → RESOURCE_EXHAUSTED, the gRPC "back off and retry" signal (the
            // analogue of the HTTP receiver's 429 + Retry-After), never a silent drop.
            Err(StoreError::Backpressure) => Err(Status::resource_exhausted(
                "evald: overloaded, retry shortly",
            )),
            Err(e) => Err(Status::unavailable(format!(
                "evald: store unavailable: {e}"
            ))),
        }
    }
}

/// Cap on a decoded OTLP/gRPC export request — mirrors the HTTP receiver's `MAX_BODY_BYTES`
/// (`ingest.rs`) rather than tonic's 4 MiB default, so a legitimately large batch export isn't
/// rejected before `ingest` ever runs.
const MAX_DECODE_BYTES: usize = 16 * 1024 * 1024;

/// Serve the OTLP/gRPC `TraceService` on `addr` until `shutdown` resolves.
pub async fn serve(
    addr: SocketAddr,
    store: Store,
    shutdown: impl std::future::Future<Output = ()> + Send + 'static,
) -> anyhow::Result<()> {
    tonic::transport::Server::builder()
        .add_service(
            TraceServiceServer::new(TraceReceiver::new(store))
                .max_decoding_message_size(MAX_DECODE_BYTES),
        )
        .serve_with_shutdown(addr, shutdown)
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::StoreConfig;
    use opentelemetry_proto::tonic::common::v1::{any_value::Value as AnyVal, AnyValue, KeyValue};
    use opentelemetry_proto::tonic::trace::v1::{ResourceSpans, ScopeSpans, Span};

    fn str_kv(key: &str, val: &str) -> KeyValue {
        KeyValue {
            key: key.to_string(),
            value: Some(AnyValue {
                value: Some(AnyVal::StringValue(val.to_string())),
            }),
            ..Default::default()
        }
    }

    fn one_span_request() -> ExportTraceServiceRequest {
        let span = Span {
            trace_id: vec![0x77; 16],
            span_id: vec![0x88; 8],
            name: "chat".to_string(),
            start_time_unix_nano: 1_000,
            end_time_unix_nano: 2_000,
            attributes: vec![
                str_kv("openinference.span.kind", "LLM"),
                str_kv("gen_ai.request.model", "gpt-4o"),
            ],
            ..Default::default()
        };
        ExportTraceServiceRequest {
            resource_spans: vec![ResourceSpans {
                scope_spans: vec![ScopeSpans {
                    spans: vec![span],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        }
    }

    #[tokio::test]
    async fn grpc_export_durably_ingests_into_the_shared_store() {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path(), StoreConfig::default()).unwrap();
        let receiver = TraceReceiver::new(store.clone());

        let resp = receiver
            .export(Request::new(one_span_request()))
            .await
            .expect("export should succeed");
        // Full success: no partial_success detail.
        assert!(resp.into_inner().partial_success.is_none());
        // append is awaited inside export, so the span is durable by the time we return.
        assert_eq!(store.span_count().unwrap(), 1);
        assert_eq!(store.trace(&"77".repeat(16)).unwrap().len(), 1);
    }

    #[tokio::test]
    async fn grpc_export_maps_backpressure_to_resource_exhausted() {
        let dir = tempfile::tempdir().unwrap();
        // Bound of 1, no compactor → the hot tier can't drain, so the second ingest sheds.
        let store = Store::open(
            dir.path(),
            StoreConfig {
                max_hot_spans: 1,
                compact_interval: None,
                ..StoreConfig::default()
            },
        )
        .unwrap();
        let receiver = TraceReceiver::new(store.clone());

        // First export fills the hot tier to its bound.
        receiver
            .export(Request::new(one_span_request()))
            .await
            .expect("first export accepted");

        // Second export is shed → RESOURCE_EXHAUSTED (the gRPC 429), not a silent drop.
        let status = receiver
            .export(Request::new(one_span_request()))
            .await
            .expect_err("second export should be shed");
        assert_eq!(status.code(), tonic::Code::ResourceExhausted);
        assert_eq!(store.span_count().unwrap(), 1);
    }
}
