//! OTLP/gRPC receiver on :4317 — the gRPC sibling of the :4318 HTTP receiver. gRPC is a
//! standard OTel collector transport, so this covers exporters that only emit OTLP/gRPC.
//!
//! Hosts the OTLP `TraceService` generated by `opentelemetry-proto` (`gen-tonic`). The
//! `export` RPC decodes into the SAME `ExportTraceServiceRequest` the HTTP path uses, so it
//! reuses the one [`crate::normalize`] pass, the blob offload, and the durable
//! [`Store::append`] — a single ingest core behind both listeners. Plaintext h2c (like the
//! :4318 HTTP receiver), for a local endpoint; front it with a TLS-terminating proxy to
//! expose it.

use std::net::SocketAddr;

use opentelemetry_proto::tonic::collector::trace::v1::{
    trace_service_server::{TraceService, TraceServiceServer},
    ExportTraceServiceRequest, ExportTraceServiceResponse,
};
use tonic::service::interceptor::InterceptedService;
use tonic::{Request, Response, Status};

use crate::{auth::Auth, normalize, Store, StoreError};

/// The gRPC receiver: a thin adapter from the OTLP `TraceService` onto the shared store.
#[derive(Clone)]
pub struct TraceReceiver {
    store: Store,
}

impl TraceReceiver {
    pub fn new(store: Store) -> Self {
        Self { store }
    }

    /// Normalize → offload oversized payloads → durably append. Shared by the `export` RPC and
    /// unit-testable without binding a socket. Returns the span count on success.
    async fn ingest(&self, request: ExportTraceServiceRequest) -> Result<usize, StoreError> {
        let mut spans = normalize::normalize_request(&request);
        let count = spans.len();
        let eval_scores = crate::evalevent::extract(&request);
        // Same single pre-storage step the HTTP door uses, so the two cannot diverge.
        // Before the offload, for the reason spelled out in `ingest.rs`: the offload writes,
        // so `append`'s guard alone would leave orphaned blobs on a full volume.
        self.store.reject_if_disk_full(count)?;
        self.store.prepare_for_storage(&mut spans);
        self.store.append(spans).await?;
        // Same step as the HTTP door: evaluation events become scores once the spans are durable.
        self.store
            .put_scores(&eval_scores)
            .map_err(StoreError::Io)?;
        Ok(count)
    }
}

#[tonic::async_trait]
impl TraceService for TraceReceiver {
    async fn export(
        &self,
        request: Request<ExportTraceServiceRequest>,
    ) -> Result<Response<ExportTraceServiceResponse>, Status> {
        match self.ingest(request.into_inner()).await {
            // Full success — an empty `partial_success` means every span was accepted.
            Ok(_) => Ok(Response::new(ExportTraceServiceResponse::default())),
            // Backpressure → RESOURCE_EXHAUSTED, the gRPC "back off and retry" signal (the
            // analogue of the HTTP receiver's 429 + Retry-After), never a silent drop.
            Err(StoreError::Backpressure) => Err(Status::resource_exhausted(
                "evald: overloaded, retry shortly",
            )),
            Err(e) => Err(Status::unavailable(format!(
                "evald: store unavailable: {e}"
            ))),
        }
    }
}

/// Cap on a decoded OTLP/gRPC export request — mirrors the HTTP receiver's `MAX_BODY_BYTES`
/// (`ingest.rs`) rather than tonic's 4 MiB default, so a legitimately large batch export isn't
/// rejected before `ingest` ever runs.
const MAX_DECODE_BYTES: usize = 16 * 1024 * 1024;

/// Serve the OTLP/gRPC `TraceService` on `addr` until `shutdown` resolves, behind the same
/// bearer-token [`Auth`] gate as the HTTP receiver. A [`disabled`](Auth::disabled) gate
/// passes every request (the default local posture); an armed gate rejects any request whose
/// `authorization` metadata is not a valid `Bearer <token>` with `UNAUTHENTICATED`.
pub async fn serve(
    addr: SocketAddr,
    store: Store,
    auth: Auth,
    shutdown: impl std::future::Future<Output = ()> + Send + 'static,
) -> anyhow::Result<()> {
    let service = TraceServiceServer::new(TraceReceiver::new(store))
        .max_decoding_message_size(MAX_DECODE_BYTES);
    // An interceptor runs on the request metadata BEFORE the message is decoded/dispatched —
    // the gRPC analogue of the HTTP receiver's outermost auth layer. `Auth::check` returns
    // true when the gate is disabled, so this is a transparent pass-through by default.
    let intercepted = InterceptedService::new(service, move |req: Request<()>| {
        authorize_metadata(&auth, req.metadata()).map(|()| req)
    });
    tonic::transport::Server::builder()
        .add_service(intercepted)
        .serve_with_shutdown(addr, shutdown)
        .await?;
    Ok(())
}

/// Authorize one gRPC request against the [`Auth`] gate from its `authorization` metadata:
/// `Ok(())` when the gate is disabled or the bearer token is valid, `UNAUTHENTICATED`
/// otherwise. Extracted from the interceptor closure so it is unit-testable without a socket.
fn authorize_metadata(auth: &Auth, md: &tonic::metadata::MetadataMap) -> Result<(), Status> {
    let header = md.get("authorization").and_then(|v| v.to_str().ok());
    if auth.check(header) {
        Ok(())
    } else {
        Err(Status::unauthenticated(
            "evald: unauthorized — set metadata authorization: Bearer <token>",
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::StoreConfig;
    use opentelemetry_proto::tonic::common::v1::{any_value::Value as AnyVal, AnyValue, KeyValue};
    use opentelemetry_proto::tonic::trace::v1::{ResourceSpans, ScopeSpans, Span};

    fn str_kv(key: &str, val: &str) -> KeyValue {
        KeyValue {
            key: key.to_string(),
            value: Some(AnyValue {
                value: Some(AnyVal::StringValue(val.to_string())),
            }),
            ..Default::default()
        }
    }

    #[test]
    fn grpc_metadata_gate_enforces_bearer_when_armed() {
        use tonic::metadata::MetadataMap;
        let auth = Auth::from_tokens(["grpc-token-0123456789"]).unwrap();

        // No `authorization` metadata → UNAUTHENTICATED.
        let empty = MetadataMap::new();
        assert!(authorize_metadata(&auth, &empty).is_err());

        // Valid bearer token → passes.
        let mut ok = MetadataMap::new();
        ok.insert(
            "authorization",
            "Bearer grpc-token-0123456789".parse().unwrap(),
        );
        assert!(authorize_metadata(&auth, &ok).is_ok());

        // Wrong token → UNAUTHENTICATED.
        let mut bad = MetadataMap::new();
        bad.insert(
            "authorization",
            "Bearer nope-nope-nope-1234567".parse().unwrap(),
        );
        assert_eq!(
            authorize_metadata(&auth, &bad).unwrap_err().code(),
            tonic::Code::Unauthenticated
        );

        // A disabled gate passes even with no metadata (default local posture).
        assert!(authorize_metadata(&Auth::disabled(), &empty).is_ok());
    }

    fn one_span_request() -> ExportTraceServiceRequest {
        let span = Span {
            trace_id: vec![0x77; 16],
            span_id: vec![0x88; 8],
            name: "chat".to_string(),
            start_time_unix_nano: 1_000,
            end_time_unix_nano: 2_000,
            attributes: vec![
                str_kv("openinference.span.kind", "LLM"),
                str_kv("gen_ai.request.model", "gpt-4o"),
            ],
            ..Default::default()
        };
        ExportTraceServiceRequest {
            resource_spans: vec![ResourceSpans {
                scope_spans: vec![ScopeSpans {
                    spans: vec![span],
                    ..Default::default()
                }],
                ..Default::default()
            }],
        }
    }

    #[tokio::test]
    async fn grpc_export_durably_ingests_into_the_shared_store() {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path(), StoreConfig::default()).unwrap();
        let receiver = TraceReceiver::new(store.clone());

        let resp = receiver
            .export(Request::new(one_span_request()))
            .await
            .expect("export should succeed");
        // Full success: no partial_success detail.
        assert!(resp.into_inner().partial_success.is_none());
        // append is awaited inside export, so the span is durable by the time we return.
        assert_eq!(store.span_count().unwrap(), 1);
        assert_eq!(store.trace(&"77".repeat(16)).unwrap().len(), 1);
    }

    #[tokio::test]
    async fn grpc_export_turns_evaluation_events_into_scores() {
        use opentelemetry_proto::tonic::trace::v1::span::Event;
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(dir.path(), StoreConfig::default()).unwrap();
        let receiver = TraceReceiver::new(store.clone());

        let mut req = one_span_request();
        req.resource_spans[0].scope_spans[0].spans[0].events = vec![Event {
            time_unix_nano: 1_500,
            name: "gen_ai.evaluation.result".into(),
            attributes: vec![
                str_kv("gen_ai.evaluation.name", "Relevance"),
                str_kv("gen_ai.evaluation.score.label", "relevant"),
            ],
            ..Default::default()
        }];
        // Send it twice: an exporter retry must not duplicate the score.
        for _ in 0..2 {
            receiver
                .export(Request::new(req.clone()))
                .await
                .expect("export");
        }
        let scores = store
            .scores_for_target(&crate::model::ScoreTarget::Span("88".repeat(8)))
            .unwrap();
        assert_eq!(scores.len(), 1);
        assert_eq!(scores[0].name, "Relevance");
        assert_eq!(scores[0].str_value.as_deref(), Some("relevant"));
    }

    #[tokio::test]
    async fn grpc_export_maps_backpressure_to_resource_exhausted() {
        let dir = tempfile::tempdir().unwrap();
        // Bound of 1, no compactor → the hot tier can't drain, so the second ingest sheds.
        let store = Store::open(
            dir.path(),
            StoreConfig {
                max_hot_spans: 1,
                compact_interval: None,
                ..StoreConfig::default()
            },
        )
        .unwrap();
        let receiver = TraceReceiver::new(store.clone());

        // First export fills the hot tier to its bound.
        receiver
            .export(Request::new(one_span_request()))
            .await
            .expect("first export accepted");

        // Second export is shed → RESOURCE_EXHAUSTED (the gRPC 429), not a silent drop.
        let status = receiver
            .export(Request::new(one_span_request()))
            .await
            .expect_err("second export should be shed");
        assert_eq!(status.code(), tonic::Code::ResourceExhausted);
        assert_eq!(store.span_count().unwrap(), 1);
    }
}
