//! Price table + cost derivation (`evald cost`, and the ingest-time fill of `cost_usd`).
//!
//! `gen_ai.*` has no cost attribute and most instrumentors do not set `llm.cost.*`, so a span
//! usually arrives with a model and token counts but no cost. This module prices those spans
//! from a table in the LiteLLM `model_prices_and_context_window.json` shape:
//!
//! * a **baseline** is compiled into the binary (`src/price_baseline.json`, regenerated by
//!   `scripts/gen_price_baseline.py`), so the default build prices out of the box;
//! * `--price-table <file>` overrides and extends it (custom / fine-tuned models). The file is
//!   re-read when its mtime changes and swapped in atomically. There is no network code:
//!   keeping the file fresh is the operator's job (`curl`, cron, config management).
//!
//! ## What is stored
//!
//! At ingest, and **only when the span carried no cost of its own**, `cost_usd` is filled
//! (rounded to 1e-12 USD, see [`round_usd`]). Nothing else is written per span. A derived cost is
//! still recognisable at read time, because a *reported* cost always comes with the attribute it
//! was read from ([`COST_ATTRIBUTES`], kept in `raw_attributes` like every attribute): "`cost_usd`
//! set and no cost attribute" means "evald derived it", which is what `evald cost --price-table`
//! re-prices. The table version that priced a block's spans is in the block's Parquet metadata
//! (`evald.price_tables`, `docs/FORMAT.md`), and the running one on `GET /v1/meta`. A per-span
//! stamp (`evald.cost.source=derived@<version>`) came first and was dropped: ~50 bytes and two
//! allocations per priced span through the WAL, the log line and the hot tier, most of the
//! measured ingest cost of pricing (`docs/BENCH-AB-GUIDE.md` §6). `evald.cost.basis` is still
//! stored, and only when the token counts were read the non-default way (below): rare, and needed
//! to re-price such a span the same way. A span-supplied cost is never overwritten. Stored values
//! mean "priced at ingest"; they are corrected at **query time**, never by rewriting.
//!
//! ## The trap: does the input count include cached tokens?
//!
//! Sources disagree (`docs/INSTRUMENTATION.md` has the per-source evidence). The OTel GenAI
//! spec and OpenAI say `input_tokens` INCLUDES cached tokens; Anthropic's raw API and Bedrock
//! Converse report them SEPARATELY. Pricing the wrong way silently double-counts or
//! under-counts. [`detect_basis`] decides from arithmetic rather than a per-SDK list: when the
//! span reports a total, `total - (prompt + completion)` says exactly what was added on top
//! (nothing, the cache tokens, the reasoning tokens, or both); without a total, cache tokens
//! larger than the whole prompt can only be additive; otherwise the spec default (included)
//! applies. Reasoning tokens are a subset of the completion unless the same arithmetic says
//! otherwise, and are priced once.
//!
//! ## Hot path
//!
//! One `Arc` clone per request (not per span), a hash lookup per span, and a handful of
//! multiplications. The slow name-normalisation path only runs when the exact model id is not
//! in the table. What a priced span costs beyond that is the 20 bytes of its `cost_usd` in the
//! WAL and on the log line; nothing else is stored for it (`docs/BENCH-AB-GUIDE.md` §6).

use std::collections::{BTreeMap, HashMap};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock, RwLock};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::Context;
use chrono::NaiveDate;
use serde_json::Value;
use sha2::{Digest, Sha256};

use crate::model::{NormalizedSpan, Tokens};

/// The table compiled into the binary.
const BASELINE_JSON: &str = include_str!("price_baseline.json");
/// How often (at most) the live table stats its file for a change.
const RELOAD_CHECK_MS: u64 = 2_000;
/// A table whose newest source is older than this triggers a warning: prices move.
pub const STALE_DAYS: i64 = 90;

/// Per-token USD rates for one tier.
#[derive(Debug, Clone, Copy, Default, PartialEq)]
struct Rates {
    input: f64,
    output: f64,
    cache_read: Option<f64>,
    cache_write: Option<f64>,
}

/// Rates that replace the base ones once a request's input passes `above` tokens.
#[derive(Debug, Clone, Copy, Default, PartialEq)]
struct Tier {
    above: u64,
    input: Option<f64>,
    output: Option<f64>,
    cache_read: Option<f64>,
    cache_write: Option<f64>,
}

/// The price of one model.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Price {
    base: Rates,
    /// Separate per-token rate for reasoning output, when the model has one.
    reasoning: Option<f64>,
    /// Ascending by threshold.
    tiers: Vec<Tier>,
}

impl Price {
    /// The rates in force for a request whose total input is `total_in` tokens: the base rates,
    /// overlaid by every tier whose threshold the request exceeds (a tier that omits a field
    /// leaves the lower tier's rate in place).
    fn rates_for(&self, total_in: u64) -> Rates {
        let mut r = self.base;
        for t in self.tiers.iter().filter(|t| total_in > t.above) {
            r.input = t.input.unwrap_or(r.input);
            r.output = t.output.unwrap_or(r.output);
            r.cache_read = t.cache_read.or(r.cache_read);
            r.cache_write = t.cache_write.or(r.cache_write);
        }
        r
    }
}

/// A set of model prices plus where it came from.
#[derive(Debug, Clone)]
pub struct PriceTable {
    /// `<commit>@<date>` of the source (or a content hash): written into every block this
    /// process flushes (`evald.price_tables`) and reported on `/v1/meta`.
    pub version: String,
    /// The newest date any source of this table is known to be as of (for the age warning).
    pub as_of: Option<NaiveDate>,
    models: HashMap<String, Price>,
}

impl PriceTable {
    /// Parse a table in the LiteLLM shape (an object of `model -> {…per-token costs…}`; entries
    /// without a per-token price, and the upstream `sample_spec` entry, are skipped). An optional
    /// `_evald` object (`commit`, `date`) names the source; without it the version is a short
    /// hash of the content.
    pub fn from_json(text: &str) -> anyhow::Result<PriceTable> {
        let root: Value = serde_json::from_str(text).context("price table is not valid JSON")?;
        let obj = root
            .as_object()
            .context("price table must be a JSON object of `model -> prices`")?;
        let meta = obj.get("_evald").and_then(Value::as_object);
        let commit = meta.and_then(|m| m.get("commit")).and_then(Value::as_str);
        let date = meta.and_then(|m| m.get("date")).and_then(Value::as_str);
        let as_of = date.and_then(parse_date);
        let version = match (commit, date) {
            // By characters, not bytes: `commit` comes from an operator's overlay file, and
            // slicing a non-ASCII value at byte 8 would panic — inside a hot reload, on the
            // ingest path.
            (Some(c), Some(d)) => format!("{}@{d}", c.chars().take(8).collect::<String>()),
            _ => format!(
                "sha256:{}",
                &hex::encode(Sha256::digest(text.as_bytes()))[..8]
            ),
        };
        let mut models = HashMap::with_capacity(obj.len());
        for (name, entry) in obj {
            if name == "_evald" || name == "sample_spec" {
                continue;
            }
            if let Some(price) = entry.as_object().and_then(parse_entry) {
                models.insert(name.to_ascii_lowercase(), price);
            }
        }
        Ok(PriceTable {
            version,
            as_of,
            models,
        })
    }

    /// The compiled-in baseline (parsed once).
    pub fn baseline() -> Arc<PriceTable> {
        static BASELINE: OnceLock<Arc<PriceTable>> = OnceLock::new();
        BASELINE
            .get_or_init(|| {
                Arc::new(
                    PriceTable::from_json(BASELINE_JSON)
                        .expect("compiled-in price baseline parses"),
                )
            })
            .clone()
    }

    /// Load a user file and lay it over the baseline: the file wins for any model it names.
    pub fn load_over_baseline(path: &Path) -> anyhow::Result<PriceTable> {
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading price table {}", path.display()))?;
        let mut over = PriceTable::from_json(&text)
            .with_context(|| format!("parsing price table {}", path.display()))?;
        // A file with no `_evald` date is as old as its last edit.
        if over.as_of.is_none() {
            over.as_of = mtime_date(path);
        }
        Ok(PriceTable::baseline().overlaid_with(over))
    }

    fn overlaid_with(&self, over: PriceTable) -> PriceTable {
        let mut models = self.models.clone();
        models.extend(over.models);
        PriceTable {
            version: format!("{}+{}", over.version, self.version),
            as_of: self.as_of.max(over.as_of),
            models,
        }
    }

    /// Number of models priced.
    pub fn len(&self) -> usize {
        self.models.len()
    }

    /// True when the table prices nothing.
    pub fn is_empty(&self) -> bool {
        self.models.is_empty()
    }

    /// Days since this table's newest source, when it is older than [`STALE_DAYS`].
    pub fn stale_days(&self, today: NaiveDate) -> Option<i64> {
        let age = (today - self.as_of?).num_days();
        (age > STALE_DAYS).then_some(age)
    }

    /// Find the price for a span's model id, returning the table key that matched.
    ///
    /// Exact match first (the common case: no allocation beyond the lookup). Otherwise the id is
    /// normalised: lowercased, leading `provider/` segments dropped, a Bedrock region prefix
    /// (`us.`) and an `@date` dropped, then trailing date/version segments (`-20250929`,
    /// `-2024-08-06`, `-v1:0`, `-latest`) removed one at a time. Every step is a hash lookup; a
    /// model that is genuinely absent stays unpriced rather than being guessed from a prefix.
    pub fn lookup(&self, model: &str) -> Option<(&str, &Price)> {
        if let Some((k, v)) = self.models.get_key_value(model) {
            return Some((k.as_str(), v));
        }
        let lower = model.to_ascii_lowercase();
        let mut rest: &str = &lower;
        loop {
            let base = rest.split('@').next().unwrap_or(rest);
            let variants = [base, strip_region(base)];
            for v in variants {
                if let Some(hit) = self.lookup_stripping_versions(v) {
                    return Some(hit);
                }
            }
            match rest.split_once('/') {
                Some((_, tail)) if !tail.is_empty() => rest = tail,
                _ => return None,
            }
        }
    }

    fn lookup_stripping_versions(&self, name: &str) -> Option<(&str, &Price)> {
        let mut cur = name;
        for _ in 0..5 {
            if let Some((k, v)) = self.models.get_key_value(cur) {
                return Some((k.as_str(), v));
            }
            match cur.rsplit_once('-') {
                Some((head, seg)) if is_version_segment(seg) && !head.is_empty() => cur = head,
                _ => return None,
            }
        }
        None
    }
}

/// `us.anthropic.claude-…` -> `anthropic.claude-…` (Bedrock cross-region inference ids).
fn strip_region(name: &str) -> &str {
    for p in [
        "us-gov.", "us.", "eu.", "apac.", "global.", "au.", "jp.", "ca.",
    ] {
        if let Some(rest) = name.strip_prefix(p) {
            return rest;
        }
    }
    name
}

/// A trailing id segment that names a snapshot rather than a model: digits (`20250929`, `0613`,
/// `08`), `v1` / `v1:0`, or `latest`. Single digits are kept (`claude-3-5`).
fn is_version_segment(seg: &str) -> bool {
    if seg == "latest" {
        return true;
    }
    if seg.len() >= 2 && seg.bytes().all(|b| b.is_ascii_digit()) {
        return true;
    }
    match seg.strip_prefix('v') {
        Some(rest) if !rest.is_empty() => {
            let (major, minor) = rest.split_once(':').unwrap_or((rest, "0"));
            major.bytes().all(|b| b.is_ascii_digit())
                && !minor.is_empty()
                && minor.bytes().all(|b| b.is_ascii_digit())
        }
        _ => false,
    }
}

/// One LiteLLM entry -> a [`Price`]; `None` when it has no per-token price at all.
fn parse_entry(e: &serde_json::Map<String, Value>) -> Option<Price> {
    let num = |k: &str| e.get(k).and_then(Value::as_f64);
    let (input, output) = (num("input_cost_per_token"), num("output_cost_per_token"));
    if input.is_none() && output.is_none() {
        return None;
    }
    let mut tiers: BTreeMap<u64, Tier> = BTreeMap::new();
    for (k, v) in e {
        let (Some((field, above)), Some(rate)) = (tier_key(k), v.as_f64()) else {
            continue;
        };
        let t = tiers.entry(above).or_insert(Tier {
            above,
            ..Tier::default()
        });
        match field {
            "input_cost_per_token" => t.input = Some(rate),
            "output_cost_per_token" => t.output = Some(rate),
            "cache_read_input_token_cost" => t.cache_read = Some(rate),
            _ => t.cache_write = Some(rate),
        }
    }
    Some(Price {
        base: Rates {
            input: input.unwrap_or(0.0),
            output: output.unwrap_or(0.0),
            cache_read: num("cache_read_input_token_cost"),
            cache_write: num("cache_creation_input_token_cost"),
        },
        reasoning: num("output_cost_per_reasoning_token"),
        tiers: tiers.into_values().collect(),
    })
}

/// `input_cost_per_token_above_200k_tokens` -> (`input_cost_per_token`, 200_000). Variants with
/// a further suffix (`…_tokens_priority`, `…above_1hr…`) do not parse and are ignored.
fn tier_key(k: &str) -> Option<(&'static str, u64)> {
    let (field, rest) = k.split_once("_above_")?;
    let field = [
        "input_cost_per_token",
        "output_cost_per_token",
        "cache_read_input_token_cost",
        "cache_creation_input_token_cost",
    ]
    .into_iter()
    .find(|f| *f == field)?;
    let n = rest.strip_suffix("_tokens")?;
    let (digits, mult) = match n.strip_suffix('k') {
        Some(d) => (d, 1_000),
        None => (n, 1),
    };
    Some((field, digits.parse::<u64>().ok()? * mult))
}

fn parse_date(s: &str) -> Option<NaiveDate> {
    let mut it = s.split('-');
    let (y, m, d) = (it.next()?, it.next()?, it.next()?);
    NaiveDate::from_ymd_opt(y.parse().ok()?, m.parse().ok()?, d.parse().ok()?)
}

fn mtime_date(path: &Path) -> Option<NaiveDate> {
    let secs = std::fs::metadata(path)
        .ok()?
        .modified()
        .ok()?
        .duration_since(UNIX_EPOCH)
        .ok()?
        .as_secs();
    chrono::DateTime::from_timestamp(secs as i64, 0).map(|d| d.date_naive())
}

/// Today (UTC), for the staleness check.
pub fn today() -> NaiveDate {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    chrono::DateTime::from_timestamp(secs as i64, 0)
        .map(|d| d.date_naive())
        .unwrap_or_default()
}

/// Log a warning when the table is old. Called at `serve` start-up and by `evald cost`.
pub fn warn_if_stale(table: &PriceTable) {
    if let Some(days) = table.stale_days(today()) {
        tracing::warn!(
            days,
            version = %table.version,
            "the model price table is {days} days old; costs derived from it may be out of date \
             (refresh it with --price-table <file>)"
        );
    }
}

// ── cost arithmetic ───────────────────────────────────────────────────────────────────────────

/// How a span's token counts relate to one another. Both default to `false`, the OTel GenAI
/// reading: cached tokens are INCLUDED in the input count, and reasoning tokens are a SUBSET of
/// the completion.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct Basis {
    /// The input count EXCLUDES cache read/write tokens (they are reported on top of it).
    pub cache_excl: bool,
    /// The completion count EXCLUDES reasoning tokens (they are reported on top of it).
    pub reasoning_add: bool,
}

impl Basis {
    /// The value stored in `evald.cost.basis`; `None` for the default (nothing stamped).
    pub fn stamp(self) -> Option<&'static str> {
        match (self.cache_excl, self.reasoning_add) {
            (false, false) => None,
            (true, false) => Some("cache_excl"),
            (false, true) => Some("reasoning_add"),
            (true, true) => Some("cache_excl,reasoning_add"),
        }
    }

    /// Inverse of [`Basis::stamp`] for a stored value.
    pub fn from_stamp(s: &str) -> Basis {
        Basis {
            cache_excl: s.contains("cache_excl"),
            reasoning_add: s.contains("reasoning_add"),
        }
    }
}

/// Decide how to read `t`. `reported_total` is the total the instrumentor itself reported (not
/// one derived as prompt + completion).
pub fn detect_basis(t: &Tokens, reported_total: Option<u64>) -> Basis {
    let p = t.prompt.unwrap_or(0);
    let c = t.completion.unwrap_or(0);
    let cache = t.cache_read.unwrap_or(0) + t.cache_write.unwrap_or(0);
    let r = t.reasoning.unwrap_or(0);
    if let Some(total) = reported_total {
        if total >= p + c {
            let extra = total - (p + c);
            // Ambiguous when the cache and reasoning counts are equal: fall through.
            if extra == 0 {
                return Basis::default();
            }
            if cache != r {
                if cache > 0 && extra == cache {
                    return Basis {
                        cache_excl: true,
                        reasoning_add: false,
                    };
                }
                if r > 0 && extra == r {
                    return Basis {
                        cache_excl: false,
                        reasoning_add: true,
                    };
                }
            }
            if cache > 0 && r > 0 && extra == cache + r {
                return Basis {
                    cache_excl: true,
                    reasoning_add: true,
                };
            }
        }
    }
    // Cache tokens cannot be part of an input count smaller than themselves.
    Basis {
        cache_excl: cache > 0 && p < cache,
        reasoning_add: false,
    }
}

/// USD for `t` at price `p`. Cached tokens and reasoning tokens are each priced exactly once.
/// The result is rounded to 1e-12 USD (see [`round_usd`]).
pub fn price_tokens(p: &Price, t: &Tokens, b: Basis) -> f64 {
    let prompt = t.prompt.unwrap_or(0);
    let comp = t.completion.unwrap_or(0);
    let cr = t.cache_read.unwrap_or(0);
    let cw = t.cache_write.unwrap_or(0);
    let r = t.reasoning.unwrap_or(0);
    let (uncached, total_in) = if b.cache_excl {
        (prompt, prompt + cr + cw)
    } else {
        (prompt.saturating_sub(cr + cw), prompt)
    };
    let (text_out, reasoning_out) = if b.reasoning_add {
        (comp, r)
    } else {
        (comp.saturating_sub(r), r)
    };
    let rates = p.rates_for(total_in);
    // An absent cache rate resolves to the input rate (no discount is invented).
    let cr_rate = rates.cache_read.unwrap_or(rates.input);
    let cw_rate = rates.cache_write.unwrap_or(rates.input);
    let reasoning_rate = p.reasoning.unwrap_or(rates.output);
    round_usd(
        uncached as f64 * rates.input
            + cr as f64 * cr_rate
            + cw as f64 * cw_rate
            + text_out as f64 * rates.output
            + reasoning_out as f64 * reasoning_rate,
    )
}

/// Round a derived cost to 1e-12 USD, at most 5e-13 USD from the exact product. A count is an
/// integer and a rate carries a few significant digits (the baseline's smallest is 1e-9 per
/// token), so the product is a short decimal; what binary floating point adds beyond it
/// (`0.020175000000000002` for `0.020175`) is noise, and it would be stored in the WAL, written
/// to the per-span log line and summed on `/metrics` for every priced span: a 20-character
/// number where an 8-character one says the same. At or above ~9 000 USD the value is returned
/// unchanged (a double that large has no fractional digits to round).
fn round_usd(usd: f64) -> f64 {
    (usd * 1e12).round() / 1e12
}

/// The attributes an instrumentor reports a cost in; [`crate::normalize`] reads `cost_usd` from
/// them in this order. Every attribute is kept in `raw_attributes`, so the presence of one of
/// these is what tells a reported cost from a derived one at read time ([`crate::cost::reprice`]).
pub const COST_ATTRIBUTES: [&str; 2] = ["llm.cost.total", "gen_ai.usage.cost"];

/// Whether `span` carries one of [`COST_ATTRIBUTES`]: a reported cost, readable or not.
pub fn has_cost_attribute(span: &NormalizedSpan) -> bool {
    COST_ATTRIBUTES
        .iter()
        .any(|k| span.raw_attributes.contains_key(*k))
}

/// The total the instrumentor reported, if it did (the normalizer fills `tokens.total` with
/// prompt + completion when absent, which would make every span look consistent).
pub fn reported_total(span: &NormalizedSpan) -> Option<u64> {
    ["llm.token_count.total", "gen_ai.usage.total_tokens"]
        .into_iter()
        .find_map(|k| span.raw_attributes.get(k).and_then(Value::as_u64))
}

/// A derived cost and how it was reached.
#[derive(Debug, Clone, Copy)]
pub struct Derived<'a> {
    pub cost: f64,
    /// The table key that matched the span's model id.
    pub model: &'a str,
    pub basis: Basis,
}

/// Price a span from its stored fields. `None` when the span already has a cost, has no model,
/// carries no prompt or completion count, or its model is not in the table.
pub fn derive<'a>(table: &'a PriceTable, span: &NormalizedSpan) -> Option<Derived<'a>> {
    if span.cost_usd.is_some() {
        return None;
    }
    let model = span.model.as_deref()?;
    if span.tokens.prompt.is_none() && span.tokens.completion.is_none() {
        return None;
    }
    let (key, price) = table.lookup(model)?;
    // A cost attribute evald could not read (a non-numeric string, say) is still the
    // instrumentor's cost: pricing over it would make the span look derived to a re-price, which
    // keys on the attribute's presence. Checked after the lookup, so an unknown model pays
    // nothing for it.
    if has_cost_attribute(span) {
        return None;
    }
    let basis = detect_basis(&span.tokens, reported_total(span));
    Some(Derived {
        cost: price_tokens(price, &span.tokens, basis),
        model: key,
        basis,
    })
}

/// Fill `cost_usd` on a span that has none (see the module docs).
pub fn apply(table: &PriceTable, span: &mut NormalizedSpan) {
    let Some(d) = derive(table, span) else {
        return;
    };
    span.cost_usd = Some(d.cost);
    // The only per-span record of how: the reading of the counts, and only when it is not the
    // default. The common case writes nothing but the cost.
    //
    // A value the caller sent under this key is dropped first. It describes how *someone else*
    // read the counts, and since a derived cost is now recognised by the absence of a cost
    // attribute, leaving it would make `evald cost --price-table` re-price this span on a basis
    // evald never used — silently, and only for the default reading, which writes nothing.
    span.raw_attributes.remove("evald.cost.basis");
    if let Some(s) = d.basis.stamp() {
        span.raw_attributes
            .insert("evald.cost.basis".into(), Value::String(s.into()));
    }
}

// ── the live table (baseline + optional hot-reloaded file) ───────────────────────────────────

struct Watch {
    path: PathBuf,
    mtime: Option<SystemTime>,
}

/// The table `serve` prices with. Reads take a brief read lock and clone an `Arc`; the file is
/// stat-ed at most every [`RELOAD_CHECK_MS`], and a changed file is parsed off to the side and
/// swapped in atomically, so a bad edit never leaves ingest without a table.
pub struct Live {
    table: RwLock<Arc<PriceTable>>,
    watch: Mutex<Option<Watch>>,
    watching: AtomicBool,
    next_check_ms: AtomicU64,
}

impl Live {
    fn new() -> Live {
        Live {
            table: RwLock::new(PriceTable::baseline()),
            watch: Mutex::new(None),
            watching: AtomicBool::new(false),
            next_check_ms: AtomicU64::new(0),
        }
    }

    /// Start pricing with `path` laid over the baseline. A file that does not parse is an error
    /// (a start-up mistake should be loud); after that, a bad edit only warns.
    pub fn watch_file(&self, path: &Path) -> anyhow::Result<()> {
        let table = PriceTable::load_over_baseline(path)?;
        *self.table.write().unwrap() = Arc::new(table);
        *self.watch.lock().unwrap() = Some(Watch {
            path: path.to_path_buf(),
            mtime: std::fs::metadata(path).and_then(|m| m.modified()).ok(),
        });
        self.watching.store(true, Ordering::Release);
        Ok(())
    }

    /// The table to price the next request with.
    pub fn table(&self) -> Arc<PriceTable> {
        if self.watching.load(Ordering::Acquire) {
            let now = now_ms();
            let due = self.next_check_ms.load(Ordering::Relaxed);
            if now >= due
                && self
                    .next_check_ms
                    .compare_exchange(
                        due,
                        now + RELOAD_CHECK_MS,
                        Ordering::Relaxed,
                        Ordering::Relaxed,
                    )
                    .is_ok()
            {
                self.reload_if_changed();
            }
        }
        self.table.read().unwrap().clone()
    }

    /// Re-read the file if its mtime moved. Public so a test (or a signal handler) can force it.
    pub fn reload_if_changed(&self) {
        let mut guard = self.watch.lock().unwrap();
        let Some(w) = guard.as_mut() else {
            return;
        };
        let mtime = std::fs::metadata(&w.path).and_then(|m| m.modified()).ok();
        if mtime == w.mtime {
            return;
        }
        // Remember the new mtime even on failure, so a broken edit warns once, not every tick.
        w.mtime = mtime;
        match PriceTable::load_over_baseline(&w.path) {
            Ok(t) => {
                tracing::info!(version = %t.version, models = t.len(), "price table reloaded");
                warn_if_stale(&t);
                *self.table.write().unwrap() = Arc::new(t);
            }
            Err(e) => {
                tracing::warn!(error = %e, "price table reload failed; keeping the previous table")
            }
        }
    }
}

fn now_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// The process-wide live table.
pub fn live() -> &'static Live {
    static LIVE: OnceLock<Live> = OnceLock::new();
    LIVE.get_or_init(Live::new)
}

/// The table to price with right now.
pub fn current() -> Arc<PriceTable> {
    live().table()
}

/// Configure the process-wide table from `--price-table` (a no-op for `None`) and warn if it is
/// old. Call once at start-up.
pub fn install(path: Option<&Path>) -> anyhow::Result<()> {
    if let Some(p) = path {
        live().watch_file(p)?;
    }
    warn_if_stale(&current());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::test_span;

    /// A tiny table with round numbers so every expected value below is hand-computable.
    /// $/token: plain in 1e-6 out 2e-6.
    fn table() -> PriceTable {
        PriceTable::from_json(
            r#"{
              "_evald": {"commit": "abcdef0123456789", "date": "2026-09-01"},
              "m-plain":  {"input_cost_per_token": 1e-6, "output_cost_per_token": 2e-6},
              "m-cache":  {"input_cost_per_token": 1e-6, "output_cost_per_token": 4e-6,
                           "cache_read_input_token_cost": 1e-7, "cache_creation_input_token_cost": 1.25e-6},
              "m-reason": {"input_cost_per_token": 1e-6, "output_cost_per_token": 4e-6,
                           "output_cost_per_reasoning_token": 8e-6},
              "m-tier":   {"input_cost_per_token": 1e-6, "output_cost_per_token": 2e-6,
                           "input_cost_per_token_above_200k_tokens": 2e-6,
                           "output_cost_per_token_above_200k_tokens": 3e-6,
                           "input_cost_per_token_above_200k_tokens_priority": 9e-6},
              "claude-sonnet-4-5": {"input_cost_per_token": 3e-6, "output_cost_per_token": 15e-6},
              "gpt-4o":            {"input_cost_per_token": 2.5e-6, "output_cost_per_token": 10e-6},
              "anthropic.claude-3-5-sonnet-20241022-v2:0": {"input_cost_per_token": 3e-6, "output_cost_per_token": 15e-6}
            }"#,
        )
        .unwrap()
    }

    fn span(model: &str, t: Tokens) -> NormalizedSpan {
        let mut s = test_span("t", "s", 1);
        s.model = Some(model.into());
        s.tokens = t;
        s
    }

    fn tok(p: u64, c: u64, cr: u64, cw: u64, r: u64) -> Tokens {
        Tokens {
            prompt: Some(p),
            completion: Some(c),
            total: Some(p + c),
            cache_read: (cr > 0).then_some(cr),
            cache_write: (cw > 0).then_some(cw),
            reasoning: (r > 0).then_some(r),
        }
    }

    fn approx(a: f64, b: f64) {
        assert!((a - b).abs() < 1e-12, "{a} != {b}");
    }

    // ── golden fixtures: the same request, in each dialect's arithmetic ───────────────────────
    //
    // Request on `m-cache`: 600 uncached input + 400 cache-read input, 200 output.
    //   600 * 1e-6  = 0.000600
    //   400 * 1e-7  = 0.000040
    //   200 * 4e-6  = 0.000800
    //   total       = 0.001440
    const GOLDEN_CACHED: f64 = 0.001440;

    #[test]
    fn otel_gen_ai_input_includes_cache_read() {
        // gen_ai.usage.input_tokens = 1000 INCLUDES the 400 cached; total_tokens reported = 1200.
        let mut s = span("m-cache", tok(1000, 200, 400, 0, 0));
        s.raw_attributes
            .insert("gen_ai.usage.total_tokens".into(), 1200.into());
        let t = table();
        let d = derive(&t, &s).unwrap();
        assert_eq!(d.basis, Basis::default());
        approx(d.cost, GOLDEN_CACHED);
    }

    #[test]
    fn openinference_anthropic_sums_the_cache_into_prompt() {
        // The OpenInference Anthropic instrumentor emits prompt = input + cache_read (+ write).
        let mut s = span("m-cache", tok(1000, 200, 400, 0, 0));
        s.raw_attributes
            .insert("llm.token_count.total".into(), 1200.into());
        approx(derive(&table(), &s).unwrap().cost, GOLDEN_CACHED);
    }

    #[test]
    fn anthropic_raw_and_bedrock_converse_report_cache_on_top() {
        // Anthropic's own `input_tokens` = 600 (uncached only), cache_read 400 separate; a
        // reported total of 1200 = 600 + 200 + 400 says the cache is on top of the prompt.
        let mut s = span("m-cache", tok(600, 200, 400, 0, 0));
        s.raw_attributes
            .insert("llm.token_count.total".into(), 1200.into());
        let t = table();
        let d = derive(&t, &s).unwrap();
        assert!(
            d.basis.cache_excl,
            "must not subtract the cache from a prompt that excludes it"
        );
        approx(d.cost, GOLDEN_CACHED); // the SAME cost as the inclusive spelling
    }

    #[test]
    fn cache_larger_than_the_prompt_can_only_be_on_top() {
        // No reported total to read: 5,000 cached tokens cannot be part of a 100-token prompt.
        let s = span("m-cache", tok(100, 10, 5000, 0, 0));
        let t = table();
        let d = derive(&t, &s).unwrap();
        assert!(d.basis.cache_excl);
        // 100*1e-6 + 5000*1e-7 + 10*4e-6
        approx(d.cost, 0.0001 + 0.0005 + 0.00004);
    }

    #[test]
    fn cache_write_is_priced_at_the_write_rate_once() {
        // 1000 input incl. 300 written to cache (1.25e-6) and 100 read (1e-7), 50 output.
        let s = span("m-cache", tok(1000, 50, 100, 300, 0));
        let expect = 600.0 * 1e-6 + 100.0 * 1e-7 + 300.0 * 1.25e-6 + 50.0 * 4e-6;
        approx(derive(&table(), &s).unwrap().cost, expect);
    }

    #[test]
    fn openai_reasoning_is_a_subset_of_the_completion_and_priced_once() {
        // completion_tokens 200 INCLUDES 150 reasoning. m-reason: text 4e-6, reasoning 8e-6.
        //   50 text * 4e-6 + 150 reasoning * 8e-6 + 1000 in * 1e-6 = 0.0002 + 0.0012 + 0.001
        let s = span("m-reason", tok(1000, 200, 0, 0, 150));
        let t = table();
        let d = derive(&t, &s).unwrap();
        assert!(!d.basis.reasoning_add);
        approx(d.cost, 0.0002 + 0.0012 + 0.001);
        // The double-count bug would have charged 200 text + 150 reasoning:
        let double = 200.0 * 4e-6 + 150.0 * 8e-6 + 1000.0 * 1e-6;
        assert!(d.cost < double);
    }

    #[test]
    fn gemini_thoughts_reported_on_top_of_the_candidates() {
        // Raw Gemini: candidates 200, thoughts 150 (separate), reported total 1350.
        let mut s = span("m-reason", tok(1000, 200, 0, 0, 150));
        s.raw_attributes
            .insert("llm.token_count.total".into(), 1350.into());
        let t = table();
        let d = derive(&t, &s).unwrap();
        assert!(d.basis.reasoning_add);
        // 200 text * 4e-6 + 150 reasoning * 8e-6 + 1000 in * 1e-6
        approx(d.cost, 0.0008 + 0.0012 + 0.001);
    }

    #[test]
    fn reasoning_without_its_own_rate_is_priced_as_output_once() {
        // m-cache has no reasoning rate: 200 completion incl. 150 reasoning => 200 * 4e-6 total.
        let s = span("m-cache", tok(0, 200, 0, 0, 150));
        approx(derive(&table(), &s).unwrap().cost, 200.0 * 4e-6);
    }

    #[test]
    fn a_missing_cache_rate_falls_back_to_the_input_rate() {
        // m-plain has no cache rates: 400 cached of 1000 are billed like ordinary input.
        let s = span("m-plain", tok(1000, 100, 400, 0, 0));
        approx(
            derive(&table(), &s).unwrap().cost,
            1000.0 * 1e-6 + 100.0 * 2e-6,
        );
    }

    #[test]
    fn a_request_over_the_tier_threshold_uses_the_tier_rates_for_everything() {
        let s = span("m-tier", tok(250_000, 1000, 0, 0, 0));
        approx(
            derive(&table(), &s).unwrap().cost,
            250_000.0 * 2e-6 + 1000.0 * 3e-6,
        );
        // At the threshold (not above) the base rates apply; `_priority` variants are ignored.
        let s = span("m-tier", tok(200_000, 1000, 0, 0, 0));
        approx(
            derive(&table(), &s).unwrap().cost,
            200_000.0 * 1e-6 + 1000.0 * 2e-6,
        );
    }

    // ── never overwrite, never guess ──────────────────────────────────────────────────────────

    #[test]
    fn a_span_supplied_cost_is_never_overwritten() {
        let mut s = span("m-plain", tok(1000, 100, 0, 0, 0));
        s.cost_usd = Some(9.99);
        apply(&table(), &mut s);
        assert_eq!(s.cost_usd, Some(9.99));
        assert!(!s.raw_attributes.contains_key("evald.cost.source"));
    }

    #[test]
    fn an_unknown_model_is_left_unpriced_not_zero() {
        let mut s = span("no-such-model-9000", tok(1000, 100, 0, 0, 0));
        apply(&table(), &mut s);
        assert_eq!(
            s.cost_usd, None,
            "unknown must stay NULL so the report can say (no price)"
        );
        assert!(!s.raw_attributes.contains_key("evald.cost.source"));
    }

    #[test]
    fn spans_without_a_model_or_counts_are_left_alone() {
        let mut s = test_span("t", "s", 1);
        apply(&table(), &mut s);
        assert_eq!(s.cost_usd, None);
        let mut s = span("m-plain", Tokens::default());
        apply(&table(), &mut s);
        assert_eq!(s.cost_usd, None);
    }

    #[test]
    fn apply_writes_the_cost_and_only_a_non_default_basis() {
        let mut s = span("m-plain", tok(1000, 100, 0, 0, 0));
        apply(&table(), &mut s);
        assert!(s.cost_usd.is_some());
        assert!(
            !s.raw_attributes.keys().any(|k| k.starts_with("evald.")),
            "the common case stores nothing per span but the cost: {:?}",
            s.raw_attributes.keys().collect::<Vec<_>>()
        );

        let mut s = span("m-cache", tok(600, 200, 400, 0, 0));
        s.raw_attributes
            .insert("llm.token_count.total".into(), 1200.into());
        apply(&table(), &mut s);
        assert_eq!(s.raw_attributes["evald.cost.basis"], "cache_excl");
    }

    #[test]
    fn a_caller_supplied_basis_is_replaced_not_trusted() {
        // The default reading stamps nothing, so a value the caller sent would survive and be
        // read back by `evald cost --price-table` as evald's own.
        let mut s = span("m-plain", tok(1000, 100, 0, 0, 0));
        s.raw_attributes.insert(
            "evald.cost.basis".into(),
            Value::String("cache_excl".into()),
        );
        apply(&table(), &mut s);
        assert!(s.cost_usd.is_some());
        assert!(
            !s.raw_attributes.contains_key("evald.cost.basis"),
            "the caller's basis must not outlive a derivation that did not use it"
        );
    }

    #[test]
    fn a_price_table_commit_is_truncated_by_characters_not_bytes() {
        // An operator's overlay names its own source; a multi-byte value must not panic.
        let t = PriceTable::from_json(
            r#"{"_evald": {"commit": "ünïcödé-commit", "date": "2026-09-01"},
                "m": {"input_cost_per_token": 1e-6, "output_cost_per_token": 2e-6}}"#,
        )
        .unwrap();
        assert_eq!(t.version, "ünïcödé-@2026-09-01");
    }

    #[test]
    fn a_cost_attribute_evald_could_not_read_still_blocks_derivation() {
        // The instrumentor set a cost the normalizer could not parse, so `cost_usd` is None.
        // Pricing it anyway would make the span look derived to a re-price, which keys on the
        // attribute's presence; it stays unpriced, as any reported cost stays untouched.
        let mut s = span("m-plain", tok(1000, 100, 0, 0, 0));
        s.raw_attributes
            .insert("llm.cost.total".into(), Value::String("n/a".into()));
        apply(&table(), &mut s);
        assert_eq!(s.cost_usd, None);
        assert!(!s.raw_attributes.contains_key("evald.cost.basis"));
    }

    // ── model-name matching ───────────────────────────────────────────────────────────────────

    #[test]
    fn model_ids_match_through_prefixes_dates_and_versions() {
        let t = table();
        let key = |m: &str| t.lookup(m).map(|(k, _)| k.to_string());
        assert_eq!(key("gpt-4o").as_deref(), Some("gpt-4o"));
        assert_eq!(key("GPT-4o").as_deref(), Some("gpt-4o"), "case-insensitive");
        assert_eq!(
            key("openai/gpt-4o").as_deref(),
            Some("gpt-4o"),
            "provider/ prefix"
        );
        assert_eq!(
            key("azure/eu/gpt-4o").as_deref(),
            Some("gpt-4o"),
            "nested prefixes"
        );
        assert_eq!(
            key("gpt-4o-2024-08-06").as_deref(),
            Some("gpt-4o"),
            "dashed date"
        );
        assert_eq!(
            key("claude-sonnet-4-5-20250929").as_deref(),
            Some("claude-sonnet-4-5")
        );
        assert_eq!(
            key("anthropic/claude-sonnet-4-5-20250929").as_deref(),
            Some("claude-sonnet-4-5")
        );
        assert_eq!(
            key("claude-sonnet-4-5@20250929").as_deref(),
            Some("claude-sonnet-4-5"),
            "vertex @date"
        );
        assert_eq!(
            key("claude-sonnet-4-5-latest").as_deref(),
            Some("claude-sonnet-4-5")
        );
        // Bedrock: exact id, the same id under a cross-region prefix, and a version bump.
        let b = "anthropic.claude-3-5-sonnet-20241022-v2:0";
        assert_eq!(key(b).as_deref(), Some(b));
        assert_eq!(key(&format!("us.{b}")).as_deref(), Some(b));
        assert_eq!(key(&format!("bedrock/eu.{b}")).as_deref(), Some(b));
    }

    #[test]
    fn matching_never_guesses_across_model_families() {
        let t = table();
        // `gpt-4o-mini` is not `gpt-4o`: only version-like segments are stripped, never words.
        assert!(t.lookup("gpt-4o-mini").is_none());
        assert!(t.lookup("gpt-4").is_none());
        assert!(t.lookup("claude-sonnet-4").is_none());
        assert!(t.lookup("").is_none());
    }

    // ── the table itself ──────────────────────────────────────────────────────────────────────

    #[test]
    fn the_compiled_in_baseline_prices_common_models() {
        let b = PriceTable::baseline();
        assert!(
            b.len() > 1000,
            "baseline should carry the text models, got {}",
            b.len()
        );
        assert!(
            b.version.contains('@'),
            "version is <commit>@<date>: {}",
            b.version
        );
        assert!(b.as_of.is_some());
        for m in ["gpt-4o", "claude-sonnet-4-5", "gemini-2.5-pro"] {
            assert!(b.lookup(m).is_some(), "baseline is missing {m}");
        }
        let (_, gpt) = b.lookup("gpt-4o").unwrap();
        assert!(gpt.base.input > 0.0 && gpt.base.output > gpt.base.input);
        assert!(
            gpt.base.cache_read.unwrap() < gpt.base.input,
            "a cache read is cheaper than input"
        );
    }

    #[test]
    fn a_user_file_overrides_and_extends_the_baseline() {
        let dir = tempfile::tempdir().unwrap();
        let f = dir.path().join("prices.json");
        std::fs::write(
            &f,
            r#"{"gpt-4o": {"input_cost_per_token": 1e-9, "output_cost_per_token": 2e-9},
                "my-finetune": {"input_cost_per_token": 5e-6, "output_cost_per_token": 6e-6}}"#,
        )
        .unwrap();
        let t = PriceTable::load_over_baseline(&f).unwrap();
        assert_eq!(
            t.lookup("gpt-4o").unwrap().1.base.input,
            1e-9,
            "the file wins"
        );
        assert_eq!(
            t.lookup("my-finetune").unwrap().1.base.output,
            6e-6,
            "and extends"
        );
        assert!(
            t.lookup("claude-sonnet-4-5").is_some(),
            "the baseline still supplies the rest"
        );
        assert!(
            t.version.contains("sha256:") && t.version.contains('+'),
            "{}",
            t.version
        );
    }

    #[test]
    fn a_table_that_is_not_json_or_not_an_object_is_an_error() {
        assert!(PriceTable::from_json("not json").is_err());
        assert!(PriceTable::from_json("[1,2]").is_err());
        assert!(PriceTable::from_json("{}").unwrap().is_empty());
    }

    // ── hot reload ────────────────────────────────────────────────────────────────────────────

    #[test]
    fn an_edited_file_is_picked_up_without_a_restart_and_a_bad_edit_keeps_the_old_table() {
        let dir = tempfile::tempdir().unwrap();
        let f = dir.path().join("prices.json");
        std::fs::write(
            &f,
            r#"{"m-x": {"input_cost_per_token": 1e-6, "output_cost_per_token": 1e-6}}"#,
        )
        .unwrap();
        let live = Live::new();
        live.watch_file(&f).unwrap();
        let price = |live: &Live| live.table().lookup("m-x").map(|(_, p)| p.base.input);
        assert_eq!(price(&live), Some(1e-6));

        // Edit the price. Bump the mtime explicitly: two writes inside one filesystem timestamp
        // tick would otherwise look unchanged.
        std::fs::write(
            &f,
            r#"{"m-x": {"input_cost_per_token": 7e-6, "output_cost_per_token": 1e-6}}"#,
        )
        .unwrap();
        bump_mtime(&f, 10);
        live.reload_if_changed();
        assert_eq!(price(&live), Some(7e-6), "the next span uses the new price");

        // A broken edit is logged and ignored; ingest keeps the last good table.
        std::fs::write(&f, "{ nope").unwrap();
        bump_mtime(&f, 20);
        live.reload_if_changed();
        assert_eq!(price(&live), Some(7e-6));

        // An unchanged file is not re-read.
        let before = live.table();
        live.reload_if_changed();
        assert!(Arc::ptr_eq(&before, &live.table()));
    }

    fn bump_mtime(path: &Path, secs_ahead: u64) {
        let f = std::fs::OpenOptions::new().write(true).open(path).unwrap();
        f.set_modified(SystemTime::now() + std::time::Duration::from_secs(secs_ahead))
            .unwrap();
    }

    #[test]
    fn a_start_up_price_table_that_does_not_parse_is_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let f = dir.path().join("bad.json");
        std::fs::write(&f, "{ nope").unwrap();
        assert!(Live::new().watch_file(&f).is_err());
        assert!(Live::new()
            .watch_file(&dir.path().join("missing.json"))
            .is_err());
    }

    // ── staleness ─────────────────────────────────────────────────────────────────────────────

    #[test]
    fn a_table_older_than_the_threshold_is_reported_stale() {
        let t = table(); // as of 2026-09-01
        let d = |y, m, dd| NaiveDate::from_ymd_opt(y, m, dd).unwrap();
        assert_eq!(t.stale_days(d(2026, 9, 30)), None, "29 days old is fine");
        assert_eq!(t.stale_days(d(2026, 11, 30)), None, "89 days old is fine");
        assert_eq!(t.stale_days(d(2026, 12, 1)), Some(91));
        // A table with no date at all cannot be judged, so it does not nag.
        assert_eq!(
            PriceTable::from_json("{}")
                .unwrap()
                .stale_days(d(2030, 1, 1)),
            None
        );
    }

    #[test]
    fn stamps_round_trip() {
        for b in [
            Basis::default(),
            Basis {
                cache_excl: true,
                reasoning_add: false,
            },
            Basis {
                cache_excl: false,
                reasoning_add: true,
            },
            Basis {
                cache_excl: true,
                reasoning_add: true,
            },
        ] {
            assert_eq!(Basis::from_stamp(b.stamp().unwrap_or("")), b);
        }
    }
}
